name: KillisEssentials
version: '${project.version}'
main: net.justkilli.killisessentials.base.Main
api-version: 1.20
authors: [ JustKilli ]
description: Some Useful things for the server

commands:
  test:
    description: Test Command
    usage: use /<command>